### ISSUE TITLE
Support custom Splunk commands

### ISSUE THREAD

**Issue by ericzinnikas** [SigmaHQ/pySigma-backend-splunk#16]
Wondering if you have any thoughts/plans on how to support custom Splunk commands (i.e. `dedup`)? It seems like these could be handled as custom type modifiers (like `re`), which would require adding to [modifier_mapping](https://github.com/SigmaHQ/pySigma/blob/7cfbe36ca4233a075f73bbda47dba0543adb0b56/sigma/modifiers.py#L229).

**Comment by thomaspatzke** [comment]
No, this would be completely opposite to the idea of Sigma to be an universal language for expression of detections.
