### ISSUE TITLE
Field mapping : "Image" field not converted for Splunk

### ISSUE THREAD

**Issue by EhouarnBeriotOConnell** [SigmaHQ/pySigma-backend-splunk#17]
Hello,

I am trying to convert some sigma rules into Splunk queries. I use pySigma like this : 
`sigma convert -t splunk -p splunk_windows rule_path`

The resulting queries keep the "Image" field as such, so my splunk app does not detect the suspicious event that it should.
e.g, the rule [Whoami execution](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_whoami.yml)  is converted into the following query : 

`Image=\\whoami.exe" OR OriginalFileName="whoami.exe`

Which works perfectly on Sysmon logs since they have an **OriginalFileName** field, but not on windows security auditing events (EventID 4688) which corresponding field is **ProcessName** (not sure that this is the exact corresponding field, but it contains the same information).

I thought about field mapping, searched [pySigma splunk backend](https://github.com/SigmaHQ/pySigma-backend-splunk) and found [this pipeline](https://github.com/SigmaHQ/pySigma-backend-splunk/blob/main/sigma/pipelines/splunk/splunk.py).

The **Image** field is indeed not mapped for windows security auditing logs. 

So, here are my questions : 
How do I convert sigma rules using the **Image** field into a Splunk query that correctly matches against windows security auditing events ?
Less specific, how do I convert a sigma rule into a Splunk query that correctly matches against any native windows event *and* Sysmon events ? 
Do I have to create a custom pipeline like described in [this doc](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html) ?

Thanks !!

**Comment by thomaspatzke** [comment]
Hi! Yes, you have to create a pipeline similar to the [Sysmon pipeline](https://github.com/SigmaHQ/pySigma-pipeline-sysmon). The [Windows pipeline project](https://github.com/SigmaHQ/pySigma-pipeline-windows/blob/main/sigma/pipelines/windows/windows.py) was intended for this purpose, but until now there's no mapping for the Image field for Security/4688 events.

**Comment by EhouarnBeriotOConnell** [comment]
Thank you for taking the time to answer me !
I have a few questions following your answer, let me know if I should create a new issue for them.

I am now trying to use a yaml file as a custom pipeline to pass with -p parameter, following [this part of the docs](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#specifying-processing-pipelines-as-yaml).
- Are there more examples somewhere to rest on ? I am having trouble with conditions.
- Is there a way to convert a sigma field condition into multiple field conditions with OR ? 
e.g `Image|endswith: 'suspicious.exe'`
Would become
`ParentImage="*suspicious.exe" OR ProcessName="*whoami.exe"`

**Comment by thomaspatzke** [comment]
If you struggle with implementing the pipeline as Python project, feel free to post the YAML source and I'm fine to integrate it into the pySigma-pipeline-windows project. Generally, the [pySigma tests](https://github.com/SigmaHQ/pySigma/tree/main/tests) are a good source for examples. For YAML there are not many because YAML is just another form of the Python representation, [this] is a test containing an example of a YAML pipeline.

**Comment by thomaspatzke** [comment]
I had to update the pySigma-windows-pipeline anyways, so I've migrated the sigmac [windows-audit](https://github.com/SigmaHQ/sigma/blob/master/tools/config/generic/windows-audit.yml) config to a pipeline. It's available in the latest version 1.1.0 of the pipeline. Please check the [condition](https://github.com/SigmaHQ/pySigma-pipeline-windows/blob/5100b2865052adba3c8c9bc013d1ab68fa170727/sigma/pipelines/windows/windows.py#L15) and [field name](https://github.com/SigmaHQ/pySigma-pipeline-windows/blob/5100b2865052adba3c8c9bc013d1ab68fa170727/sigma/pipelines/windows/windows.py#L117) mapping. It might be incomplete, so pull requests are much appreciated!

**Comment by EhouarnBeriotOConnell** [comment]
Thank you so much !

This will help me understand better how the whole thing works.
Your update covers exactly what I need for now, but I'll make sure to PR if I need anything !
Thank you for your awesome work, and for the help <3

(Link in your first message is broken 😺 )
