### ISSUE TITLE
Field Mapping: Add OriginalFileName -> Processes.original_file_name

### ISSUE THREAD

**Issue by Rivosyke** [SigmaHQ/pySigma-backend-splunk#20]
In the file below, it looks like OriginalFileName is missing from the `splunk_sysmon_process_creation_cim_mapping` dict. 

Splunk added `Processes.original_file_name` in CIM v4.20.2.

https://github.com/SigmaHQ/pySigma-backend-splunk/blob/main/sigma/pipelines/splunk/splunk.py

**Comment by thomaspatzke** [comment]
Thanks for the hint! Can you provide a pull request?

**Comment by Rivosyke** [comment]
I was going to but didn't know if there were other sections that needed modification as well. Looks like maybe the tests need to be updated to include that as well but I'll give it a looksee.

**Comment by thomaspatzke** [comment]
Now it works 😉
