### ISSUE TITLE
Single quoting of field names breaking SPL

### ISSUE THREAD

**Issue by xv-nathan-h** [SigmaHQ/pySigma-backend-splunk#7]
I just updated to v0.3.4 and had one of my generated SPL queries break due to the change in the handling of field names with spaces introduced in commit 84b19e6. It appears that this line is setting the transformer to use single quotes (sigma/backends/splunk/splunk.py line 38)
```
    field_quote: ClassVar[str] = "'"
```
The generated SPL then has single quotes around the field name, which at least Splunk Cloud 8.2.2203.3 does not work with. Changing the single quotes to double quotes seems to work fine. I'm not sure if there's potentially a Splunk version difference around this or not.

**Comment by thomaspatzke** [comment]
@d1vious @P4T12ICK can you confirm that field names with spaces must be quoted with double quotes `"``? I inferred the single quote for the search command from the eval usage.

**Comment by thomaspatzke** [comment]
Just confirmed myself 😉 In search context it's indeed the double quote. I fix this...

@d1vious @P4T12ICK new todo: improve the Splunk docs 😁😉

**Comment by thomaspatzke** [comment]
Fixed!
